from .build import build_model_from_cfg
import models.TopNet
import models.PoinTr
import models.GRNet
import models.PCN
import models.FoldingNet
import models.cov
import models.AE
import models.AEC
import models.Gan
import models.Gan1
import models.Gan2
import models.disp3d
import models.disptr
import models.upptr
import models.disptr1
import models.pmpptr
import models.pmpptr1
import models.pmpptr2
import models.poolptr
import models.seedptr
import models.seedptr1
import models.seedptr2
import models.moveptr
import models.seedpmp
import models.fineptr
import models.fineptr1
import models.fineptr2
import models.fineptr3
import models.fineptr4
import models.fineptr5
import models.fineptr6
import models.fineptr7
import models.fineptr22
import models.fineptr52
import models.fineptr53
import models.fineptr54
import models.snow
import models.fineptr520
import models.fineptr521
import models.fineptr522
import models.fineptr523
import models.fineptr524
import models.FBNet
import models.VRCNet
import models.SDNet
import models.SDNet1
import models.SDNet2
import models.covNet
import models.dualNet
import models.dualNet1
import models.dualNet2
import models.finenet
import models.adapointr
import models.dualNet3